### ISSUE TITLE
Cross origin issue with latest release, breaking other widgets

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame-jupyter-extension#7]
6191d2d seems to have broken use of trame with jupyter-server-proxy and is affecting other third party libraries.

After installing `trame-jupyter-extension==2.1.1`, I see `chrome-error://chromewebdata/` when trying to use trame over jupyter-server-proxy

Further, this is affecting other thrid party software. For instance, if I try to use `ipyleaflet` at all after this upgrade, I see `net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep` errors when loading any basemap tiles

```py
from ipyleaflet import Map
Map()
```
<img width="800" alt="Screenshot 2024-06-16 at 10 55 25 PM" src="https://github.com/Kitware/trame-jupyter-extension/assets/22067021/68b59a35-4023-4a0d-b9b8-8cfd3f5da72c">

Downgrading to `trame-jupyter-extension==2.1.0` yields correct behavior

**Comment by jourdain** [comment]
yes... We will need to go the route of service worker to properly enable WASM... I may push a temporary fix that only enable those cross origin option with some ENV vars...

**Comment by jourdain** [comment]
Should be fixed in 2.1.2

**Comment by jourdain** [comment]
For reference https://web.dev/articles/coop-coep

**Comment by jourdain** [comment]
Ideally leaflet should take some extra args to allow the fetching of the tiles/images...
